package pik.clminputdata.tools;

public class NoConvergenceException extends Exception {

	/**
	 * SUID generated by eclipse
	 */
	private static final long serialVersionUID = 1913504929784577833L;

	private final double result;
	
	public NoConvergenceException(String str, double result) {
		super(str);
		this.result = result;
	}

	public double getResult() {
		return result;
	}
		
}
