package pik.clminputdata.tools;

/**
 * Exception in case of a non-convergence of an algorithm.
 * 
 * The latest (hopefully best) result is stored.
 * 
 * @author Sebastian Schubert
 * 
 */
public class NoConvergenceException extends Exception {

	/**
	 * SUID generated by eclipse
	 */
	private static final long serialVersionUID = 1913504929784577833L;

	/**
	 * Latest result.
	 */
	private final double result;

	/**
	 * Constructor.
	 * 
	 * @param str
	 *            Error message
	 * @param result
	 *            Latest result of non-converging algorithm
	 */
	public NoConvergenceException(String str, double result) {
		super(str);
		this.result = result;
	}

	/**
	 * Get the latest (hopefully best) result of the non-converging algorithm.
	 * 
	 * @return Latest result of non-converging algorithm
	 */
	public double getResult() {
		return result;
	}

}
